services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    ports:
      - "3000:3000/tcp"    # İlk kurulum portu
      - "8080:80/tcp"      # AdGuard Dashboard (Kurulumdan sonra)
      - "53:53/udp"        # DNS Portu
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    depends_on:
      - adguardhome
    environment:
      - WG_PASSWORD=342835.#
      - WG_HOST=vpn.apprain.io
      - WG_PORT=443
      - WG_MTU=1420
      - WG_DEFAULT_DNS=10.8.0.1 # AdGuard'ın VPN içindeki IP'si
      - WG_ALLOWED_IPS=0.0.0.0/0
      - TZ=Europe/Istanbul
    volumes:
      - .:/etc/wireguard
    ports:
      - "443:443/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
