services:
  # --- 1. DOMAIN YONETICISI ---
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      vpn_net:
        ipv4_address: 172.28.0.5

  # --- 2. TAKIP SISTEMI ---
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime_kuma_data:/app/data
    networks:
      vpn_net:
        ipv4_address: 172.28.0.20

  # --- 3. VPN ---
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    # BURAYA DIKKAT: environment kisminda ARTIK PASSWORD_HASH YOK!
    # env_file zaten o isi halledecek.
    environment:
      - WG_HOST=52.57.113.222
      - WG_PORT=51820
      - WG_DEFAULT_DNS=172.28.0.10
      - WG_MTU=1280
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=25
    env_file:
      - .env
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "443:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      vpn_net:
        ipv4_address: 172.28.0.2

  # --- 4. REKLAM ENGELLEYICI ---
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    networks:
      vpn_net:
        ipv4_address: 172.28.0.10

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
