services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.apprain.io
      - PASSWORD=AppRain2026
      - WG_PORT=443
      - WG_DEFAULT_DNS=172.28.0.10
      - WG_MTU=1280
      - WG_ALLOWED_IPS=0.0.0.0/0
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "443:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      vpn_net:
        ipv4_address: 172.28.0.2

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "80:80/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    networks:
      vpn_net:
        ipv4_address: 172.28.0.10

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
